// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsjsomrmiknndaorljnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzanNvbXJtaWtubmRhb3Jsam5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTk3NzMsImV4cCI6MjA3MTk5NTc3M30.QdbA04IXmUXMjsSYiVgg3e1ahBkjReNXkQRpQxOnX5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});